[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/', 
    '@solmate=lib/solmate/src/', 
    'forge-std/=lib/forge-std/src/'  # Added forge-std remapping
]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# See more config options at the Foundry GitHub repository:
# https://github.com/foundry-rs/foundry/tree/master/config
# 
# Example of additional configuration options:
# 
# [profile.release]
# optimize = true
# 
# [profile.dev]
# src = "contracts"
# out = "build"
# 
# [ffi]
# allowed = true
